services:
  - type: web
    name: telegram-clicker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 